[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'hyperhyphen'
version = "1.0.0"
requires-python = ">= 3.7"

[tool.setuptools.packages.find]
include = ["hyperhyphen"]

[tool.distutils.bdist_wheel]
py-limited-api = "cp37"